### ISSUE TITLE
Can't get this to work on Amazon Linux 2

### ISSUE THREAD

**Issue by MeStrak** [stuartsan/cypress-lambda#4]
Hi Stuart, I ❤️ this project!

Unfortunately I'm totally stuck and can't deploy ...

I was able to get it running using the lambci node 8.10 Docker. However I couldn't deploy it as only 10.x and 12.x are supported in AWS now.

In the update to 10.x, Amazon also made the lambda environment Amazon Linux 2, which comes with a lot less basic libraries installed: https://cloudbriefly.com/post/exploring-the-aws-lambda-execution-environment/

For example tar isn't installed, but I got round that easily using an npm package.

The problem I have is that when the script gets to the point of running Xvfb. There are lots of shared libraries missing.

I found a hacky way to get round a lot of these using the approach documented here: https://aws.amazon.com/premiumsupport/knowledge-center/lambda-linux-binary-package/

Unfortunately I'm now totally stuck on the following error:
`./Xvfb: error while loading shared libraries: libsystemd.so.0: cannot open shared object file: No such file or directory`

I tried to use the same approach as above with the library systemd.x86_64, but it seems to have a different structure to the other libraries and doesn't work.

Have you tried to update to Amazon Linux 2 with more success than me? Am I missing something obvious? I'm quite a n00b when it comes to this type of script, I guess a lot of this could be done directly in your normal setup script instead of the manual download I was doing?

**Comment by MeStrak** [comment]
Ok so I managed to get that dependency and some others using Centos rpm packages, but now I have something else:

./Xvfb: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /var/task/libsystemd.so.0)
./Xvfb: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/libmount.so.1)
./Xvfb: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/libblkid.so.1)
./Xvfb: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/libuuid.so.1)

**Comment by MeStrak** [comment]
Right, sorry for the quite frequent updates, it's just incase anyone is looking at this and is confused (like me)!

My issue was that the centos dependencies were the wrong version. I managed to get the right ones and now I'm on to a different error, actually fixed by Stuart in the original blog post:

XKB: Failed to compile keymap
Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.

Will keep looking later, I guess some of my changes reverted the fux from @stuartsan.

**Comment by MeStrak** [comment]
So everything seems ok, the Xvfb patch has been applied, but I still get an error. The full log is below (from `DEBUG=xvfb /app/node_modules/.bin/cypress run`)
```
  xvfb lock filename /tmp/.X99-lock +0ms
  xvfb lock filename /tmp/.X99-lock +1ms
  xvfb setting DISPLAY :99 +0ms
  xvfb all Xvfb arguments [ ':99' ] +2ms
  xvfb checking if started by looking for the lock file /tmp/.X99-lock +7ms
  xvfb checking if started by looking for the lock file /tmp/.X99-lock +17ms
  xvfb lock file /tmp/.X99-lock found after 10 ms +1ms
  xvfb xvfb closed with error code 1 +11ms
  xvfb after receiving signal null +0ms
  xvfb and stderr output +0ms
  xvfb XKB: Failed to compile keymap
  xvfb Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.
  xvfb (EE) 
  xvfb Fatal server error:
  xvfb (EE) Failed to activate virtual core keyboard: 2(EE) 
  xvfb  +0ms
  xvfb XVFB spawn failed +0ms
  xvfb Error: XKB: Failed to compile keymap
  xvfb Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.
  xvfb (EE) 
  xvfb Fatal server error:
  xvfb (EE) Failed to activate virtual core keyboard: 2(EE) 
  xvfb 
  xvfb     at ChildProcess.<anonymous> (/app/node_modules/@cypress/xvfb/index.js:189:23)
  xvfb     at ChildProcess.emit (events.js:310:20)
  xvfb     at maybeClose (internal/child_process.js:1021:16)
  xvfb     at Socket.<anonymous> (internal/child_process.js:443:11)
  xvfb     at Socket.emit (events.js:310:20)
  xvfb     at Pipe.<anonymous> (net.js:672:12) +1ms
  xvfb restoring process.env.DISPLAY variable +44ms
  xvfb lock filename /tmp/.X99-lock +0ms
  xvfb lock file /tmp/.X99-lock +0ms
  xvfb lock file /tmp/.X99-lock not found when stopping +1ms
```


I really can't figure out why though, doesn't seem to be a permissions issue, and I don't know how to get any more detailed logs.

@stuartsan any ideas? Have you looked at an upgrade to the new lambda environment?

**Comment by 2-X** [comment]
how did you end up getting this to work?
